env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10
      script:
        - set -o pipefail
        - xcodebuild test -scheme DataSourceKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild test -scheme Demo -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c

notifications:
  email: false
